name: Deploy Song Game to GitHub Pages
on:
  push:
    branches:
      - main  # Deploy v1.5.0 to root
      - develop  # Deploy v2.0.0-beta to /v2.0.0-beta
  workflow_dispatch:  # Allow manual trigger
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Deploy Version 1.5.0 to Root
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: .
          publish_branch: main
      - name: Deploy Version 2.0.0-beta to Subfolder
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: v2.0.0-beta
          publish_branch: main
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4